name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          wrapper-directory: gradle/wrapper
          gradle-executable: gradlew
          allow-snapshots: true
          min-wrapper-count: 1
        
      - name: Build
        run: ./gradlew clean build

      - name: Test
        run: ./gradlew test --tests "*"
